CREATE OR REPLACE EXTERNAL TABLE RAW_DB.COVID19.EXT_JHU_TIMESERIES(
    UID NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c1')::VARCHAR)),
    FIPS NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c2')::VARCHAR)),
    ISO2 VARCHAR(2) AS (GET(VALUE, 'c3')::VARCHAR),
    ISO3 VARCHAR(3) AS (GET(VALUE, 'c4')::VARCHAR),
    CODE3 NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c5')::VARCHAR)),
    ADMIN2 VARCHAR(100) AS (GET(VALUE, 'c6')::VARCHAR),
    LATITUDE FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c7')::VARCHAR)),
    LONGITUDE FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c8')::VARCHAR)),
    PROVINCE_STATE VARCHAR(100) AS (GET(VALUE, 'c9')::VARCHAR),
    COUNTRY_REGION VARCHAR(100) AS (GET(VALUE, 'c10')::VARCHAR),
    DATE DATE AS (TRY_TO_DATE(GET(VALUE, 'c11')::VARCHAR)),
    CONFIRMED NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c12')::VARCHAR)),
    DEATHS NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c13')::VARCHAR)),
    RECOVERED NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c14')::VARCHAR))
)
LOCATION = @RAW_DB.COVID19.COVID19_S3_STAGE/
FILE_FORMAT = RAW_DB.COVID19.CSV_FORMAT
COMMENT = 'JHU COVID-19 時系列データ'