CREATE OR REPLACE EXTERNAL TABLE RAW_DB.COVID19.EXT_COVID19_WORLD_TESTING(
    ISO_CODE VARCHAR(10) AS (GET(VALUE, 'c1')::VARCHAR),
    CONTINENT VARCHAR(50) AS (GET(VALUE, 'c2')::VARCHAR),
    LOCATION VARCHAR(100) AS (GET(VALUE, 'c3')::VARCHAR),
    DATE DATE AS (TRY_TO_DATE(GET(VALUE, 'c4')::VARCHAR)),
    TOTAL_CASES NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c5')::VARCHAR)),
    NEW_CASES NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c6')::VARCHAR)),
    NEW_CASES_SMOOTHED FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c7')::VARCHAR)),
    TOTAL_DEATHS NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c8')::VARCHAR)),
    NEW_DEATHS NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c9')::VARCHAR)),
    NEW_DEATHS_SMOOTHED FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c10')::VARCHAR)),
    NEW_TESTS NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c26')::VARCHAR)),
    TOTAL_TESTS NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c27')::VARCHAR)),
    POSITIVE_RATE FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c32')::VARCHAR)),
    TOTAL_VACCINATIONS NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c35')::VARCHAR)),
    PEOPLE_VACCINATED NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c36')::VARCHAR)),
    PEOPLE_FULLY_VACCINATED NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c37')::VARCHAR)),
    TOTAL_BOOSTERS NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c38')::VARCHAR)),
    ICU_PATIENTS NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c18')::VARCHAR)),
    HOSP_PATIENTS NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c20')::VARCHAR)),
    HOSPITAL_BEDS_PER_THOUSAND FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c58')::VARCHAR)),
    POPULATION NUMBER(38,0) AS (TRY_TO_NUMBER(GET(VALUE, 'c46')::VARCHAR)),
    POPULATION_DENSITY FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c47')::VARCHAR)),
    MEDIAN_AGE FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c48')::VARCHAR)),
    AGED_65_OLDER FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c49')::VARCHAR)),
    AGED_70_OLDER FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c50')::VARCHAR)),
    GDP_PER_CAPITA FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c51')::VARCHAR)),
    DIABETES_PREVALENCE FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c54')::VARCHAR)),
    CARDIOVASC_DEATH_RATE FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c53')::VARCHAR)),
    LIFE_EXPECTANCY FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c59')::VARCHAR)),
    HUMAN_DEVELOPMENT_INDEX FLOAT AS (TRY_TO_DOUBLE(GET(VALUE, 'c60')::VARCHAR))
)
LOCATION = @RAW_DB.COVID19.COVID19_WORLD_TESTING_STAGE
FILE_FORMAT = RAW_DB.COVID19.CSV_FORMAT
COMMENT = 'COVID-19 world testing, vaccination, hospital 
data